Update lists.ad
apache/incubator pull request #84
Opened 2020-12-26 15:10 UTC by cottage14

Minor text edits.

2020-12-27 05:18 UTC, justinmclean reviewed
"1general1"?

2020-12-28 19:10 UTC, dave2wave requested changes

2020-12-28 19:10 UTC, dave2wave commented on pages/guides/lists.ad
> +This email alias is for the `dev` lists for all active podlings. We use it for incubator-wide announcements so podling participants don't need to subscribe to 1general1 to get all information. Send e
Minor edit required

2020-12-28 19:26 UTC, dave2wave approved these changes

2020-12-28 19:27 UTC, merged